# Generated by Django 2.1.5 on 2019-04-11 21:22

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190327_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_slug', models.CharField(max_length=128)),
                ('tag_name', models.CharField(max_length=128)),
                ('tag_id', models.PositiveIntegerField(default=0)),
                ('tag_count', models.PositiveIntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
