# Generated by Django 2.1.5 on 2019-04-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20190411_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_name', models.CharField(max_length=128)),
                ('priority_id', models.PositiveIntegerField(default=0)),
                ('priority_count', models.PositiveIntegerField(db_index=True, default=0)),
            ],
        ),
    ]
